import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/_header/Header";
import Footer from "./components/_footer/Footer";
import { Providers } from "./redux/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lavinia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <Providers>
          {children}
        </Providers>
        <Footer/>
      </body>
    </html>
  );
}
